//Wetter-Links
export const allLinks = {
    Wetter:{
        subtitle: 'Wo blästs?',
        links:[
            {
                title:'Textprognose', 
                link:'http://www.meteoschweiz.admin.ch/home.html?tab=report'
            },
            {
                title:'Frontenkarte', 
                link:'http://www.meteoschweiz.admin.ch/home/wetter/prognosen/allgemeine-lage.html'
            },
            {
                title:'kk7', 
                link:'https://wetter.kk7.ch/'
            },
            {
                title:'Meteocentrale', 
                link:'http://www.meteocentrale.ch/de/wetter/wetterstationen.html'
            },
            {
                title:'Burnair-Prognose', 
                link:'https://www.burnair.ch/MeteoService/'
            },
            {
                title:'Gleitschirmmeteo', 
                link:'http://gleitschirmmeteo.ch/'
            }
        ]
    },

    Thermik:{
        subtitle: 'Wo steigts?',
        links:[
            {
                title:'Soaringmeteo', 
                link:'https://soaringmeteo.org/soarWRF2K0612Z.html'
            },
            {
                title:'Regtherm', 
                link:'https://wetter.kk7.ch/#regtherm'
            },
            {
                title:'Hotspots', 
                link:'https://thermal.kk7.ch/'
            },
            {
                title:'SHV-Meteo', 
                link:'https://www.meteo-shv.ch/home/allgemein/segelflugwetterbericht.html'
            },
            {
                title:'Interlaken-Visp', 
                link:'https://www.meteo-shv.ch/home/thermik/previtemps-72-std-interlaken-visp.html'
            },
            {
                title:'Interlaken-Visp', 
                link:'https://www.meteo-shv.ch/home/thermik/previtemps-72-std-interlaken-visp.html'
            },
            {
                title:'Buochs-Locarno', 
                link:'https://www.meteo-shv.ch/home/thermik/previtemps-72-std-interlaken-visp.html'
            },
            {
                title:'Visp-Illanz', 
                link:'https://www.meteo-shv.ch/home/thermik/previtemps-72-std-visp-illanz.html'
            },
            {
                title:'Ilanz-Samedan', 
                link:'https://www.meteo-shv.ch/home/thermik/previtemps-72-std-illanz-samedan.html'
            }
        ]
    },
        
    Wind:{
        subtitle: 'Wo blästs?',
        links:[
            {
                title:'Föhndiagramm', 
                link:'http://www.meteocentrale.ch/de/wetter/foehn-und-bise/foehn.html'
            },
            {
                title:'Bisendiagramm', 
                link:'http://www.meteocentrale.ch/de/wetter/foehn-und-bise/bise.html'
            },
            {
                title:'Meteocentrale', 
                link:'http://wetterstationen.meteomedia.ch/?map=Schweiz'
            },
            {
                title:'Live-Wind-Karte', 
                link:'https://www.burnair.ch/windmap/'
            },
            {
                title:'Weissenstein', 
                link:'https://www.dcweissenstein.ch/portfolio_page/wetterstation-weissenstein/'
            },
            {
                title:'Uetliberg', 
                link:'http://www.meteocentrale.ch/de/europa/schweiz/wetter-uetliberg-turm/details/S066770/#2017-04-03'
            },
            {
                title:'Rigi-Kulm', 
                link:'http://wetterstationen.meteomedia.ch/?map=Schweiz&station=066561'
            },
            {
                title:'Weissenstein – Röti', 
                link:'https://www.dcweissenstein.ch/portfolio_page/wetterstation-roeti/'
            }
        ]
    },

    Webcams:{
        subtitle: 'Wie siehts aus?',
        links:[
            {
                title:'Engelbergerthal', 
                link:'https://www.flugsau.ch/main_bigware_30.php?pages_id=21&language=de'
            },
            {
                title:'Brunni-Engelberg', 
                link:'http://www.brunni.ch/aktuelle-info/webcams'
            },
            {
                title:'Eggberge', 
                link:'http://www.eggberge.ch/aktuell/webcam'
            },
            {
                title:'Rotenflue', 
                link:'http://www.mythenregion.ch/winter/info/webcams'
            },
            {
                title:'Cimetta', 
                link:'https://www.bergfex.ch/locarno-orselina-cardada/webcams/c7865/'
            },
            {
                title:'Niederbauen', 
                link:'http://www.niederbauen.ch/aussichten/webcams'
            },
            {
                title:'Laax', 
                link:'https://laax.roundshot.com/crap-sogn-gion-park'
            },
            {
                title:'Grindelwald', 
                link:'https://panocam.skiline.cc/firstbahn#'
            },
            {
                title:'Fiesch – Landeplatz', 
                link:'http://flug-taxi.ch/webcam/landeplatz_fiesch.jpg'
            }
        ]
    },

    Karten:{
        subtitle: 'Das wichtigste Kartenmaterial.',
        links:[
            {
                title:'DABS von Heute', 
                link:'https://www.skybriefing.com/portal/delegate/dabs?today'
            },
            {
                title:'DABS von Morgen', 
                link:'https://www.skybriefing.com/portal/delegate/dabs?tomorrow'
            },
            {
                title:'Segelflugkarte', 
                link:'https://map.geo.admin.ch/?lang=de&zoom=3&scale=500000&X=261310.48&Y=687075.00&bgLayer=ch.swisstopo.pixelkarte-farbe&bgOpacity=1&topic=ech&layers=ch.bazl.segelflugkarte'
            },
            {
                title:'Hinderniskarte', 
                link:'https://map.geo.admin.ch/?lang=de&zoom=4&scale=500000&X=169415.73694&Y=635750&layers=ch.bazl.segelflugkarte&bgLayer=ch.swisstopo.pixelkarte-farbe&bgOpacity=1&topic=ech'
            },
            {
                title:'Gleitwinkel', 
                link:'http://www.parange.ch'
            },
            {
                title:'XC-Weeks', 
                link:'http://xcweeks.com'
            },
            {
                title:'XC-Planer', 
                link:'https://xcplanner.appspot.com'
            }
        ]
    },

    Diverse:{
        subtitle: 'Weitere nützliche Klicks',
        links:[
            {
                title:'SHV Lufträume', 
                link:'https://www.shv-fsvl.ch/sicherheit/luftraum'
            },
            {
                title:'SHV Fluggebiete', 
                link:'https://www.shv-fsvl.ch/sicherheit/fluggebiete'
            },
            {
                title:'XContest', 
                link:'https://www.xcontest.org/world/en/flights/daily-score-pg/#filter[date]=2018-02-11@filter[country]=CH'
            },
            {
                title:'Manövervideos', 
                link:'https://www.youtube.com/user/glidezeit/videos?shelf_id=1&view=0&sort=dd'
            },
            {
                title:'Leg. Segelflugkarte', 
                link:'http://api3.geo.admin.ch/static/images/legends/ch.bazl.segelflugkarte_de_big.pdf'
            },
            {
                title:'Luftraum News', 
                link:'https://www.shv-fsvl.ch/sicherheit/luftraum/'
            },
            {
                title:'Lokale Abmachungen', 
                link:'http://www.5steps.ch/meteo/lokaleAbmachungen.htm'
            }
        ]
    }
}